export interface CityData {
  id: string;
  nameKo: string;
  nameEn: string;
  country: string;
  countryFlag: string;
  timezone: string;
  utcOffset: number;
  currency: string;
  currencyCode: string;
  lat: number;
  lon: number;
  tagline: string;
  gradient: string;
}

export const cities: CityData[] = [
  {
    id: "seoul",
    nameKo: "서울",
    nameEn: "Seoul",
    country: "한국",
    countryFlag: "\uD83C\uDDF0\uD83C\uDDF7",
    timezone: "Asia/Seoul",
    utcOffset: 9,
    currency: "원",
    currencyCode: "KRW",
    lat: 37.5665,
    lon: 126.978,
    tagline: "네버 슬립, 네버 스탑",
    gradient: "from-rose-500 to-orange-400",
  },
  {
    id: "tokyo",
    nameKo: "도쿄",
    nameEn: "Tokyo",
    country: "일본",
    countryFlag: "\uD83C\uDDEF\uD83C\uDDF5",
    timezone: "Asia/Tokyo",
    utcOffset: 9,
    currency: "엔",
    currencyCode: "JPY",
    lat: 35.6762,
    lon: 139.6503,
    tagline: "질서 속의 카오스",
    gradient: "from-pink-500 to-red-400",
  },
  {
    id: "osaka",
    nameKo: "오사카",
    nameEn: "Osaka",
    country: "일본",
    countryFlag: "\uD83C\uDDEF\uD83C\uDDF5",
    timezone: "Asia/Tokyo",
    utcOffset: 9,
    currency: "엔",
    currencyCode: "JPY",
    lat: 34.6937,
    lon: 135.5023,
    tagline: "먹다 죽어도 좋아",
    gradient: "from-amber-500 to-yellow-400",
  },
  {
    id: "bangkok",
    nameKo: "방콕",
    nameEn: "Bangkok",
    country: "태국",
    countryFlag: "\uD83C\uDDF9\uD83C\uDDED",
    timezone: "Asia/Bangkok",
    utcOffset: 7,
    currency: "바트",
    currencyCode: "THB",
    lat: 13.7563,
    lon: 100.5018,
    tagline: "천사의 도시, 악마의 유혹",
    gradient: "from-yellow-500 to-amber-400",
  },
  {
    id: "danang",
    nameKo: "다낭",
    nameEn: "Da Nang",
    country: "베트남",
    countryFlag: "\uD83C\uDDFB\uD83C\uDDF3",
    timezone: "Asia/Ho_Chi_Minh",
    utcOffset: 7,
    currency: "동",
    currencyCode: "VND",
    lat: 16.0544,
    lon: 108.2022,
    tagline: "가성비 끝판왕 해변",
    gradient: "from-cyan-500 to-teal-400",
  },
  {
    id: "singapore",
    nameKo: "싱가포르",
    nameEn: "Singapore",
    country: "싱가포르",
    countryFlag: "\uD83C\uDDF8\uD83C\uDDEC",
    timezone: "Asia/Singapore",
    utcOffset: 8,
    currency: "달러",
    currencyCode: "SGD",
    lat: 1.3521,
    lon: 103.8198,
    tagline: "깨끗함의 끝, 벌금의 시작",
    gradient: "from-emerald-500 to-green-400",
  },
  {
    id: "taipei",
    nameKo: "타이베이",
    nameEn: "Taipei",
    country: "대만",
    countryFlag: "\uD83C\uDDF9\uD83C\uDDFC",
    timezone: "Asia/Taipei",
    utcOffset: 8,
    currency: "달러",
    currencyCode: "TWD",
    lat: 25.033,
    lon: 121.5654,
    tagline: "야시장 그 자체",
    gradient: "from-violet-500 to-purple-400",
  },
  {
    id: "hongkong",
    nameKo: "홍콩",
    nameEn: "Hong Kong",
    country: "홍콩",
    countryFlag: "\uD83C\uDDED\uD83C\uDDF0",
    timezone: "Asia/Hong_Kong",
    utcOffset: 8,
    currency: "달러",
    currencyCode: "HKD",
    lat: 22.3193,
    lon: 114.1694,
    tagline: "네온사인 아래 딤섬",
    gradient: "from-red-500 to-rose-400",
  },
  {
    id: "bali",
    nameKo: "발리",
    nameEn: "Bali",
    country: "인도네시아",
    countryFlag: "\uD83C\uDDEE\uD83C\uDDE9",
    timezone: "Asia/Makassar",
    utcOffset: 8,
    currency: "루피아",
    currencyCode: "IDR",
    lat: -8.3405,
    lon: 115.092,
    tagline: "영혼의 힐링 성지",
    gradient: "from-lime-500 to-emerald-400",
  },
  {
    id: "paris",
    nameKo: "파리",
    nameEn: "Paris",
    country: "프랑스",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    timezone: "Europe/Paris",
    utcOffset: 2,
    currency: "유로",
    currencyCode: "EUR",
    lat: 48.8566,
    lon: 2.3522,
    tagline: "낭만 그 이상, 그 이하",
    gradient: "from-blue-500 to-indigo-400",
  },
  {
    id: "newyork",
    nameKo: "뉴욕",
    nameEn: "New York",
    country: "미국",
    countryFlag: "\uD83C\uDDFA\uD83C\uDDF8",
    timezone: "America/New_York",
    utcOffset: -4,
    currency: "달러",
    currencyCode: "USD",
    lat: 40.7128,
    lon: -74.006,
    tagline: "잠들지 않는 도시",
    gradient: "from-slate-500 to-zinc-400",
  },
  {
    id: "london",
    nameKo: "런던",
    nameEn: "London",
    country: "영국",
    countryFlag: "\uD83C\uDDEC\uD83C\uDDE7",
    timezone: "Europe/London",
    utcOffset: 1,
    currency: "파운드",
    currencyCode: "GBP",
    lat: 51.5074,
    lon: -0.1278,
    tagline: "비와 함께 산책",
    gradient: "from-gray-500 to-blue-400",
  },
];

export function getCityByEn(name: string): CityData | undefined {
  return cities.find(
    (c) => c.nameEn.toLowerCase() === name.toLowerCase() || c.id === name.toLowerCase()
  );
}
